name: PromptAPI
main: eDroid\PromptAPI\Main
version: 1.0.0
api: [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
load: POSTWORLD
author: eDroid
description: Prompt player for input
website: https://github.com/eDroiid/PromptAPI